// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by AgileObjects.AgileMapper.Buildable.
// Runtime Version: 0.1.0.0
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using AgileObjects.AgileMapper.Buildable.UnitTests.Mappers;
using AgileObjects.AgileMapper.UnitTests.Common.TestClasses;

namespace AgileObjects.AgileMapper.Buildable.UnitTests.Mappers.Extensions
{
    [GeneratedCode("AgileObjects.AgileMapper.Buildable", "0.1.0.0")]
    public static class MappingExtensions
    {
        public static AddressMapper Map
        (
            this Address source
        )
        {
            return new AddressMapper(source);
        }

        public static CharArrayMapper Map
        (
            this char[] source
        )
        {
            return new CharArrayMapper(source);
        }

        public static ChildMapper Map
        (
            this Child source
        )
        {
            return new ChildMapper(source);
        }

        public static DateTimeHashSetMapper Map
        (
            this HashSet<DateTime> source
        )
        {
            return new DateTimeHashSetMapper(source);
        }

        public static DecimalArrayMapper Map
        (
            this decimal[] source
        )
        {
            return new DecimalArrayMapper(source);
        }

        public static IntAddressPublicTwoFieldsMapper Map
        (
            this PublicTwoFields<int, Address> source
        )
        {
            return new IntAddressPublicTwoFieldsMapper(source);
        }

        public static IntArrayMapper Map
        (
            this int[] source
        )
        {
            return new IntArrayMapper(source);
        }

        public static IntIEnumerableMapper Map
        (
            this IEnumerable<int> source
        )
        {
            return new IntIEnumerableMapper(source);
        }

        public static IntStringIntToTargetValueSourceMapper Map
        (
            this ToTargetValueSource<int, string, int> source
        )
        {
            return new IntStringIntToTargetValueSourceMapper(source);
        }

        public static ProductArrayMapper Map
        (
            this Product[] source
        )
        {
            return new ProductArrayMapper(source);
        }

        public static ProductDtoArrayMapper Map
        (
            this ProductDto[] source
        )
        {
            return new ProductDtoArrayMapper(source);
        }

        public static ProductDtoListMapper Map
        (
            this List<ProductDto> source
        )
        {
            return new ProductDtoListMapper(source);
        }

        public static ProductMapper Map
        (
            this Product source
        )
        {
            return new ProductMapper(source);
        }

        public static StringCollectionMapper Map
        (
            this Collection<string> source
        )
        {
            return new StringCollectionMapper(source);
        }

        public static StringListMapper Map
        (
            this List<string> source
        )
        {
            return new StringListMapper(source);
        }

        public static StringMapper Map
        (
            this string source
        )
        {
            return new StringMapper(source);
        }

        public static StringPublicFieldMapper Map
        (
            this PublicField<string> source
        )
        {
            return new StringPublicFieldMapper(source);
        }

        public static StringPublicPropertyMapper Map
        (
            this PublicProperty<string> source
        )
        {
            return new StringPublicPropertyMapper(source);
        }

        public static StringStringDictionaryMapper Map
        (
            this Dictionary<string, string> source
        )
        {
            return new StringStringDictionaryMapper(source);
        }
    }
}