// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by AgileObjects.AgileMapper.Buildable.
// Runtime Version: 0.1.0.0
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using AgileObjects.AgileMapper;
using AgileObjects.AgileMapper.ObjectPopulation;
using AgileObjects.AgileMapper.UnitTests.Common.TestClasses;

namespace AgileObjects.AgileMapper.Buildable.UnitTests.Mappers
{
    [GeneratedCode("AgileObjects.AgileMapper.Buildable", "0.1.0.0")]
    public class AddressMapper : MappingExecutionContextBase<Address>
    {
        public AddressMapper
        (
            Address source
        )
        : base(source)
        {
        }

        public Address Over
        (
            Address target
        )
        {
            return AddressMapper.Overwrite(this.CreateRootMappingData(target));
        }

        private static Address Overwrite
        (
            IObjectMappingData<Address, Address> aToAData
        )
        {
            try
            {
                aToAData.Target.Line1 = aToAData.Source.Line1;
                aToAData.Target.Line2 = aToAData.Source.Line2;

                return aToAData.Target;
            }
            catch (Exception ex)
            {
                throw MappingException.For(
                    "Overwrite",
                    "Address",
                    "Address",
                    ex);
            }
        }
    }
}