// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by AgileObjects.AgileMapper.Buildable.
// Runtime Version: 0.1.0.0
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using AgileObjects.AgileMapper.UnitTests.Common.TestClasses;

namespace AgileObjects.AgileMapper.Buildable.UnitTests.Mappers
{
    [GeneratedCode("AgileObjects.AgileMapper.Buildable", "0.1.0.0")]
    public static class Mapper
    {
        public static AddressMapper Map
        (
            Address source
        )
        {
            return new AddressMapper(source);
        }

        public static DateTimesMapper Map
        (
            HashSet<DateTime> source
        )
        {
            return new DateTimesMapper(source);
        }

        public static IntArrayMapper Map
        (
            int[] source
        )
        {
            return new IntArrayMapper(source);
        }

        public static ProductDtosMapper Map
        (
            List<ProductDto> source
        )
        {
            return new ProductDtosMapper(source);
        }

        public static PublicField_StringMapper Map
        (
            PublicField<string> source
        )
        {
            return new PublicField_StringMapper(source);
        }

        public static PublicProperty_StringMapper Map
        (
            PublicProperty<string> source
        )
        {
            return new PublicProperty_StringMapper(source);
        }

        public static StringMapper Map
        (
            string source
        )
        {
            return new StringMapper(source);
        }

        public static StringsMapper Map
        (
            List<string> source
        )
        {
            return new StringsMapper(source);
        }
    }
}