// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by AgileObjects.AgileMapper.Buildable.
// Runtime Version: 0.1.0.0
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Linq;
using AgileObjects.AgileMapper;
using AgileObjects.AgileMapper.Extensions;
using AgileObjects.AgileMapper.ObjectPopulation;

namespace AgileObjects.AgileMapper.Buildable.UnitTests.Mappers
{
    [GeneratedCode("AgileObjects.AgileMapper.Buildable", "0.1.0.0")]
    public class CharArrayMapper : MappingExecutionContextBase<char[]>
    {
        public CharArrayMapper
        (
            char[] source
        )
        : base(source)
        {
        }

        public int[] Over
        (
            int[] target
        )
        {
            return CharArrayMapper.Overwrite(this.CreateRootMappingData(target));
        }

        private static int[] Overwrite
        (
            IObjectMappingData<char[], int[]> caToIaData
        )
        {
            try
            {
                return caToIaData.Source.Project(c => CharArrayMapper.GetInt(c)).ToArray();
            }
            catch (Exception ex)
            {
                throw MappingException.For(
                    "Overwrite",
                    "char[]",
                    "int[]",
                    ex);
            }
        }

        private static int GetInt
        (
            char c
        )
        {
            int intValue;
            return int.TryParse(c.ToString(), out intValue) ? intValue : default(int);
        }
    }
}